# Generated by Django 3.2.5 on 2021-08-02 10:40

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/images/default.png', force_format=None, keep_meta=True, null=True, quality=0, size=[400, 400], upload_to=users.models.user_image_dir),
        ),
    ]
