# Generated by Django 3.2.5 on 2021-07-24 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import todolist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[100, 100], upload_to=todolist.models.user_image_dir)),
                ('is_status', models.BooleanField(default=False)),
                ('sum_todo', models.IntegerField(default=False, editable=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Важные и срочные'), (2, 'Важные и несрочные'), (3, 'Неважные и несрочные')], default=3, verbose_name='Приоритет')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('complete', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(null=True, to='todolist.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.profile')),
            ],
            options={
                'ordering': ['complete'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.subcategory')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.task')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
    ]
